import type { AppData } from "./types";

const now = new Date().toISOString();

export const seedData: AppData = {
  organizations: [
    {
      id: "org-1",
      name: "示例办公设备有限公司",
      entityType: "企业",
      roles: ["客户"],
      unifiedCreditCode: "91370000DEMO001",
      legalPerson: "张示例",
      phone: "18764401666",
      city: "示例市",
      invoiceInfo: "示例办公设备有限公司 / 税号 91370000DEMO001",
      status: "正常",
      createdAt: now,
    },
    {
      id: "org-2",
      name: "示例区政务服务中心",
      entityType: "政府",
      roles: ["使用单位"],
      city: "示例市",
      district: "示例区",
      address: "示例市示例区政务路 5 号",
      status: "正常",
      createdAt: now,
    },
    {
      id: "org-3",
      name: "示例品牌官方渠道有限公司",
      entityType: "企业",
      roles: ["供应商"],
      unifiedCreditCode: "91370000DEMO002",
      legalPerson: "李渠道",
      phone: "15600000000",
      bankInfo: "中国工商银行佛山北滘支行 2013013919200104312",
      status: "正常",
      createdAt: now,
    },
    {
      id: "org-4",
      name: "示例暖通设备有限公司",
      entityType: "企业",
      roles: ["供应商"],
      unifiedCreditCode: "91370000DEMO003",
      legalPerson: "王渠道",
      phone: "15500000000",
      status: "正常",
      createdAt: now,
    },
    {
      id: "org-5",
      name: "示例智能科技有限公司",
      entityType: "企业",
      roles: ["客户", "平台入驻客户"],
      unifiedCreditCode: "91370000DEMO005",
      legalPerson: "赵入驻",
      phone: "13065056229",
      email: "demo1@example.com",
      city: "示例市",
      status: "正常",
      createdAt: now,
    },
    {
      id: "org-6",
      name: "示例商贸有限公司",
      entityType: "企业",
      roles: ["客户", "平台入驻客户"],
      unifiedCreditCode: "91370000DEMO006",
      legalPerson: "钱入驻",
      phone: "13964862000",
      city: "示例市",
      status: "正常",
      createdAt: now,
    },
  ],
  products: [
    {
      id: "prd-1",
      code: "25MDKT-001",
      name: "KFR-26GW/G3-1 示例品牌挂机 大1匹 1级",
      kind: "实体商品",
      category: "空调",
      capacity: "大1匹",
      energyLevel: "1级",
      shape: "挂机",
      frameworkPrice: 2170,
      passThroughPrice: 1870,
      quotePrice: 1830,
      costPrice: 1730,
      platformCode: "31022010009528",
      description: "框架协议商品，含13%增值税专用发票。",
    },
    {
      id: "prd-2",
      code: "25MDKT-003",
      name: "KFR-35GW/G3-1A 示例品牌挂机 1.5匹 1级",
      kind: "实体商品",
      category: "空调",
      capacity: "1.5匹",
      energyLevel: "1级",
      shape: "挂机",
      frameworkPrice: 2380,
      passThroughPrice: 1950,
      quotePrice: 1900,
      costPrice: 1750,
      platformCode: "31022010010428",
    },
    {
      id: "prd-3",
      code: "FW-RZ-001",
      name: "泉E采/青慧采平台入驻服务",
      kind: "虚拟服务",
      category: "平台入驻",
      quotePrice: 2000,
      costPrice: 0,
      description: "付款后启动，营业执照 OCR 快速建档，统一入驻流程。",
    },
  ],
  supplierPrices: [
    { id: "sp-1", productId: "prd-1", supplierOrgId: "org-3", purchasePrice: 1730, note: "官方渠道" },
    { id: "sp-2", productId: "prd-1", supplierOrgId: "org-4", purchasePrice: 1710, note: "备用渠道" },
    { id: "sp-3", productId: "prd-2", supplierOrgId: "org-3", purchasePrice: 1750 },
  ],
  projects: [
    {
      id: "pj-1",
      projectNo: "XM20260619001",
      name: "示例政务服务中心空调采购",
      type: "实体商品",
      customerOrgId: "org-1",
      usageUnitOrgId: "org-2",
      sourcePlatform: "框架协议",
      owner: "王云磊",
      status: "待采购/平台操作",
      contractStatus: "待签",
      paymentStatus: "已收",
      purchaseStatus: "待采购",
      invoiceStatus: "未开",
      totalAmount: 1830,
      totalCost: 1730,
      currentBlocker: "待采购下单",
      updatedAt: now,
    },
    {
      id: "pj-2",
      projectNo: "XM20260624002",
      name: "示例智能科技平台入驻",
      type: "平台入驻服务",
      customerOrgId: "org-5",
      sourcePlatform: "泉E采",
      owner: "平平",
      status: "已付款待办理",
      contractStatus: "无需",
      paymentStatus: "已收",
      purchaseStatus: "无需采购",
      invoiceStatus: "未开",
      totalAmount: 2000,
      totalCost: 0,
      currentBlocker: "域名备案等待客户接听电话",
      updatedAt: now,
    },
    {
      id: "pj-3",
      projectNo: "XM20260624003",
      name: "示例商贸入驻续办",
      type: "平台入驻服务",
      customerOrgId: "org-6",
      sourcePlatform: "青慧采",
      owner: "崔金龙",
      status: "异常",
      contractStatus: "无需",
      paymentStatus: "已收",
      purchaseStatus: "无需采购",
      invoiceStatus: "未开",
      totalAmount: 1000,
      totalCost: 0,
      currentBlocker: "客户营业执照变更未完成",
      updatedAt: now,
    },
  ],
  projectItems: [
    { id: "pi-1", projectId: "pj-1", productId: "prd-1", productName: "KFR-26GW/G3-1 示例品牌挂机 大1匹 1级", quantity: 1, actualPrice: 1830, costPrice: 1730 },
    { id: "pi-2", projectId: "pj-2", productId: "prd-3", productName: "泉E采/青慧采平台入驻服务", quantity: 1, actualPrice: 2000, costPrice: 0 },
    { id: "pi-3", projectId: "pj-3", productId: "prd-3", productName: "泉E采/青慧采平台入驻服务", quantity: 1, actualPrice: 1000, costPrice: 0 },
  ],
  onboardingRecords: [
    {
      id: "ob-1",
      projectId: "pj-2",
      customerOrgId: "org-5",
      platform: "泉E采",
      step: "域名备案中",
      salesOwner: "刘亚楠",
      businessLicenseNo: "91370000DEMO005",
      qiluAccount: "S_xinyuznkj",
      supplierAccount: "qiluyiju",
      domain: "xinyu-ai.com",
      icpRecordNo: "1ede269d-c2cc-4225-9205-afb79fbd0962",
      licenseDisplayStatus: "未处理",
      publicSecurityStatus: "未处理",
      backendTemplateStatus: "已录入",
      caStatus: "未办理",
      serviceYears: 2,
      note: "域名备案等待客户接听电话。",
    },
    {
      id: "ob-2",
      projectId: "pj-3",
      customerOrgId: "org-6",
      platform: "青慧采",
      step: "异常",
      salesOwner: "崔金龙",
      businessLicenseNo: "91370000DEMO006",
      qiluAccount: "S_qdhhtsm",
      licenseDisplayStatus: "未处理",
      publicSecurityStatus: "未处理",
      backendTemplateStatus: "已录入",
      caStatus: "未办理",
      serviceYears: 1,
      note: "等待客户变更营业执照。",
    },
  ],
  invoices: [
    { id: "inv-1", projectId: "pj-1", type: "销项", counterpartyOrgId: "org-1", amount: 1830, status: "待确认" },
    { id: "inv-2", projectId: "pj-2", type: "销项", counterpartyOrgId: "org-5", amount: 2000, status: "草稿" },
  ],
  transactions: [
    { id: "tx-1", projectId: "pj-1", type: "收款", amount: 1830, date: "2026-06-19", status: "已匹配" },
    { id: "tx-2", projectId: "pj-2", type: "收款", amount: 2000, date: "2026-06-24", status: "已匹配" },
    { id: "tx-3", projectId: "pj-3", type: "收款", amount: 1000, date: "2026-06-24", status: "已匹配" },
  ],
  ocrJobs: [
    {
      id: "ocr-1",
      type: "营业执照",
      fileName: "营业执照-示例智能.png",
      status: "待确认",
      result: {
        企业名称: "示例智能科技有限公司",
        统一社会信用代码: "91370000DEMO005",
        法定代表人: "赵入驻",
        类型: "有限责任公司",
      },
      createdAt: now,
    },
  ],
};
